apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: myvcs

resources:
  - ../../base

images:
  - name: myvcs
    newName: registry.gitlab.com/duttashivani06/myvcs_project
    newTag: 74e63507

patches:
  - target:
      kind: Job
      name: myvcs-help

    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always

  - target:
      kind: Deployment
      name: myvcs

    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always