apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: myvcs

resources:
  - ../../base

images:
  - name: myvcs
    newName: myvcs-test
    newTag: latest

patches:
  - target:
      kind: Job
      name: myvcs-help
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
      - op: add
        path: /spec/template/spec/securityContext/runAsUser
        value: 1000
      - op: add
        path: /spec/template/spec/securityContext/runAsGroup
        value: 1000