apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: myvcs-repository
  labels:
    app.kubernetes.io/name: myvcs
    app.kubernetes.io/component: storage

spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: standard

  resources:
    requests:
      storage: 1Gi